#!/bin/sh
#
#

rm -rf autom4te.cache
rm -f Makefile.in Makefile configure aclocal.m4 config.h.in
rm -f */Makefile.in */Makefile

{ find build-aux -type f  \
      | grep -v 'clean$' | grep -v '/bootstrap$' | grep -v '/[.]gitignore$'

} | xargs rm -f

rm -f */version.tex

