#!/bin/sh

# Acute - A C Unit Testing Environment
# Copyright (C) 2019 M E Leypold
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

try(){
    INDEX=$1
    shift
    echo "** trying: $*"
    if "$@"; then
	echo "ok $INDEX # ["'$?'"=$?] $*"
    else
	echo "not ok $INDEX # ["'$?'"=$?] $*"
    fi
    return 0
}

srcdir="$(realpath "$(dirname "$0")"/../example-project)"
unset TEST_LOGS
unset MAKEFLAGS

echo 1..3
rm -rf $0.build
mkdir $0.build

( cd "$srcdir"
  if test -f Makefile; then
      make distclean
  fi
)

( cd $0.build
  try 1 $srcdir/configure
  try 2 make
)
unset srcdir
set >$0.env
( cd $0.build
  unset srcdir
  make check
)                                   \
| awk '/^Testsuite/{$NF=""}/^PASS|FAIL/,/^See/{print}'  \
> $0.check-out 2>&1
try 3 cmp $0.check-out $0.expected-out
exit 0




