#!/bin/sh
#
# Acute - A C Unit Testing Environment
# Copyright (C) 2019 M E Leypold
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Bootstrap a source copy newly checked out from a development
# version.
#
# See also: https://stackoverflow.com/questions/3290908/which-files-generated-by-autotools-should-i-keep-in-version-control-repository
#
# The idea is, that there we distinguish ...

autoreconf --install
( cd example-project 
  build-aux/bootstrap
)
CFLAGS="-g -Wall -Werror -Wextra --std=gnu11 " "$(dirname "$(dirname "$(realpath "$0")")")"/configure
make

